services:
  nrtm4serve:
    image: docker.io/etchells/nrtm4serve:latest
    ports:
      - "8000:8080"
    environment:
      - PG_DATABASE_URL=postgres://nrtm4@host.docker.internal:15432/postgres?sslmode=disable
      - NRTM4_FILE_PATH=/nrtm4-files
    volumes:
      - ./nrtm4-files:/nrtm4-files
    depends_on:
      - postgresql
    healthcheck:
      test:
        ["CMD-SHELL", "curl --silent --fail http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - db

  postgresql:
    image: docker.io/library/postgres:17
    command: >
      -c max_wal_size=2048
    user: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db
    ports:
      - "15432:5432"

networks:
  db:
